In [43]:
#Handling missing values

import pandas as pd
df = pd.read_csv('sales.csv')
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD
1,B-26055,5729,64,NaN,Furniture,Chairs,EMI
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI
3,B-26093,2847,712,8.0,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4.0,Electronics,Phones,Credit Card

In [44]:
df.isnull()

      Order ID  Amount  Profit  Quantity  Category  Sub-Category  PaymentMode
0        False   False   False     False     False         False        False
1        False   False   False      True     False         False        False
2        False   False   False     False     False         False        False
3        False   False   False     False     False         False        False
4        False   False   False     False     False         False        False
...        ...     ...     ...       ...       ...           ...          ...
1495     False   False   False     False     False         False        False
1496     False   False   False     False     False         False        False
1497     False   False   False     False     False         False        False
1498     False   False   False     False     False         False        False
1499     False   False   False     False     False         False        False

[1500 rows x 7 columns]

In [45]:
df.isnull().any(axis=1)     #if there is any null value or missing value then True will be shown against that row no. and axis=1 basically takes all columns together

0       False
1        True
2       False
3       False
4       False
        ...
1495    False
1496    False
1497    False
1498    False
1499    False
Length: 1500, dtype: bool

In [46]:
df.isnull().sum()   #how many total null values are there in each col

Order ID        0
Amount          0
Profit          0
Quantity        1
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [47]:
# fills the missing values with 0

df_filled = df.fillna(0)
df_filled.head(3)

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD
1,B-26055,5729,64,0.0,Furniture,Chairs,EMI
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI

In [48]:
#filling missing values with mean of the column
df['Qty_fillNA'] = df['Quantity'].fillna(df['Quantity'].mean())
df

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode,Qty_fillNA
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD,7.000000
1,B-26055,5729,64,NaN,Furniture,Chairs,EMI,3.736491
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI,8.000000
3,B-26093,2847,712,8.0,Electronics,Printers,Credit Card,8.000000
4,B-25602,2617,1151,4.0,Electronics,Phones,Credit Card,4.000000
...,...,...,...,...,...,...,...,...
1495,B-25700,7,-3,2.0,Clothing,Hankerchief,COD,2.000000
1496,B-25757,3151,-35,7.0,Clothing,Trousers,EMI,7.000000
1497,B-25973,4141,1698,13.0,Electronics,Printers,COD,13.000000
1498,B-25698,7,-2,1.0,Clothing,Hankerchief,COD,1.000000
1499,B-25993,4363,305,5.0,Furniture,Tables,EMI,5.000000

In [50]:
df.dtypes

Order ID         object
Amount            int64
Profit            int64
Quantity        float64
Category         object
Sub-Category     object
PaymentMode      object
Qty_fillNA      float64
dtype: object

In [51]:
df = df.rename(columns = {'Quantity':'Net Qty'})
df.head()

,Order ID,Amount,Profit,Net Qty,Category,Sub-Category,PaymentMode,Qty_fillNA
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD,7.000000
1,B-26055,5729,64,NaN,Furniture,Chairs,EMI,3.736491
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI,8.000000
3,B-26093,2847,712,8.0,Electronics,Printers,Credit Card,8.000000
4,B-25602,2617,1151,4.0,Electronics,Phones,Credit Card,4.000000

In [53]:
#Change data type

df['Profit_new'] = df['Profit'].astype(float)
df.head()

,Order ID,Amount,Profit,Net Qty,Category,Sub-Category,PaymentMode,Qty_fillNA,Profit_new
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD,7.000000,658.0
1,B-26055,5729,64,NaN,Furniture,Chairs,EMI,3.736491,64.0
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI,8.000000,146.0
3,B-26093,2847,712,8.0,Electronics,Printers,Credit Card,8.000000,712.0
4,B-25602,2617,1151,4.0,Electronics,Phones,Credit Card,4.000000,1151.0

In [54]:
## if we want to apply any func to all the values of a col

df['New Qty']=df['Net Qty'].apply(lambda x:x**2)
df.head()

,Order ID,Amount,Profit,Net Qty,Category,Sub-Category,PaymentMode,Qty_fillNA,Profit_new,New Qty
0,B-25681,1096,658,7.0,Electronics,Electronic Games,COD,7.000000,658.0,49.0
1,B-26055,5729,64,NaN,Furniture,Chairs,EMI,3.736491,64.0,NaN
2,B-25955,2927,146,8.0,Furniture,Bookcases,EMI,8.000000,146.0,64.0
3,B-26093,2847,712,8.0,Electronics,Printers,Credit Card,8.000000,712.0,64.0
4,B-25602,2617,1151,4.0,Electronics,Phones,Credit Card,4.000000,1151.0,16.0

In [55]:
## Data aggregating and grouping

#grouping category on the basis of mean of their net qty sold
grouped_mean = df.groupby('Category')['Net Qty'].mean()
print(grouped_mean)

Category
Clothing       3.704953
Electronics    3.746753
Furniture      3.847107
Name: Net Qty, dtype: float64

In [56]:
grouped_sum = df.groupby(['Category','Sub-Category'])['Net Qty'].sum()
print(grouped_sum)

Category     Sub-Category
Clothing     Hankerchief         741.0
             Kurti               164.0
             Leggings            186.0
             Saree               795.0
             Shirt               271.0
             Skirt               248.0
             Stole               671.0
             T-shirt             305.0
             Trousers            135.0
Electronics  Accessories         262.0
             Electronic Games    297.0
             Phones              304.0
             Printers            291.0
Furniture    Bookcases           297.0
             Chairs              263.0
             Furnishings         310.0
             Tables               61.0
Name: Net Qty, dtype: float64

In [57]:
df.groupby(['Category','Sub-Category'])['Net Qty'].mean()

Category     Sub-Category
Clothing     Hankerchief         3.761421
             Kurti               3.489362
             Leggings            3.509434
             Saree               3.767773
             Shirt               3.927536
             Skirt               3.875000
             Stole               3.494792
             T-shirt             3.961039
             Trousers            3.461538
Electronics  Accessories         3.638889
             Electronic Games    3.759494
             Phones              3.662651
             Printers            3.932432
Furniture    Bookcases           3.759494
             Chairs              3.602740
             Furnishings         4.246575
             Tables              3.588235
Name: Net Qty, dtype: float64

In [58]:
## grouping multiple cols with multiple aggregate functions

grouped_agg = df.groupby(['Category','Sub-Category'])['Net Qty'].agg(['mean','sum','count'])
grouped_agg

                                  mean    sum  count
Category    Sub-Category
Clothing    Hankerchief       3.761421  741.0    197
            Kurti             3.489362  164.0     47
            Leggings          3.509434  186.0     53
            Saree             3.767773  795.0    211
            Shirt             3.927536  271.0     69
            Skirt             3.875000  248.0     64
            Stole             3.494792  671.0    192
            T-shirt           3.961039  305.0     77
            Trousers          3.461538  135.0     39
Electronics Accessories       3.638889  262.0     72
            Electronic Games  3.759494  297.0     79
            Phones            3.662651  304.0     83
            Printers          3.932432  291.0     74
Furniture   Bookcases         3.759494  297.0     79
            Chairs            3.602740  263.0     73
            Furnishings       4.246575  310.0     73
            Tables            3.588235   61.0     17

In [16]:
## Joining operations

data = [
    {'Key':'A','Value1':1},
    {'Key':'B','Value1':2},
    {'Key':'C','Value1':3}
]
df1 = pd.DataFrame(data)
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value2':[4,5,6]})

In [17]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [18]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [19]:
#inner join on key column

pd.merge(df1,df2,on='Key',how = 'inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [20]:
#outer join on key column

pd.merge(df1,df2,on='Key',how = 'outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [21]:
#left outer join on key column

pd.merge(df1,df2,on='Key',how = 'left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [22]:
#right outer join on key column

pd.merge(df1,df2,on='Key',how = 'right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6