In [3]:
#Handling missing values

import pandas as pd
df = pd.read_csv('sales.csv')
df.head()

,Order ID,Amount,Profit,Quantity,Category,Sub-Category,PaymentMode
0,B-25681,1096,658,7,Electronics,Electronic Games,COD
1,B-26055,5729,64,14,Furniture,Chairs,EMI
2,B-25955,2927,146,8,Furniture,Bookcases,EMI
3,B-26093,2847,712,8,Electronics,Printers,Credit Card
4,B-25602,2617,1151,4,Electronics,Phones,Credit Card

In [10]:
df.isnull()

      Order ID  Amount  Profit  Quantity  Category  Sub-Category  PaymentMode
0        False   False   False     False     False         False        False
1        False   False   False     False     False         False        False
2        False   False   False     False     False         False        False
3        False   False   False     False     False         False        False
4        False   False   False     False     False         False        False
...        ...     ...     ...       ...       ...           ...          ...
1495     False   False   False     False     False         False        False
1496     False   False   False     False     False         False        False
1497     False   False   False     False     False         False        False
1498     False   False   False     False     False         False        False
1499     False   False   False     False     False         False        False

[1500 rows x 7 columns]

In [11]:
df.isnull().any(axis=1)     #if there is any null value or missing value then True will be shown against that row no. and axis=1 basically takes all columns together

0       False
1       False
2       False
3       False
4       False
        ...
1495    False
1496    False
1497    False
1498    False
1499    False
Length: 1500, dtype: bool

In [12]:
df.isnull().sum()

Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
dtype: int64

In [ ]:
# fills the missing values with 0

df_filled = df.fillna(0)

In [16]:
#filling missing values with mean of the column
df['Sales_fillNA'] = df['Sales'].fillna(df['Sales'].mean())
df

KeyError: 'Sales'